package com.smms.meeting_service.domain;
public enum NotificationType {
    MEETING_REMINDER, MEETING_SCHEDULED, MEETING_CANCELLED, MEETING_RESCHEDULED,
    SLOT_ASSIGNED, SLOT_RESPONSE, MEETING_REQUEST, ESCALATION_ALERT,
    ALLOCATION_NOTICE, FORM_REQUEST, FORM_SUBMITTED, PROFILE_UPDATE_REQUEST,
    PROFILE_UPDATE_RESULT, SYSTEM_ALERT
}
