server:
  port: ${CONFIG_PORT:8888}

spring:

  application:
    name: config-server
  
  #config server will use the native profile to read configuration files from the classpath
  profiles:
    active: native

  #Location where the config server will look for configuration files
  cloud:
    config:
      server:
        native:
          # Config files location — inside the JAR classpath
          search-locations: classpath:/config

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:${DISCOVERY_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: INFO